### ISSUE TITLE
Setup ORM layer to default to snake_case pluralized table names

### ISSUE THREAD

**Issue by acorncom** [denali-js/denali#108]
per our Gitter discussion, we want to have the default for table names be the following:

- model name of `issue` -> table name `issues`
- model name (`BlogPost`) -> table name `blog_posts`

This should be overridable at the model level ( @davewasmer do we want to add a method call of some kind at the ApplicationModel level to allow overriding this across the board if needed? )

**Comment by davewasmer** [comment]
Just to clarify - Denali core has no concept of table names. We have "model types", which is a string identifier for each model class. The default value of a model's type is derived from it's class name, which might be switching to `snake_case` by default. So the `BlogPost.type === 'blog_post'`.

But this is deliberately **not** a table name. Because "table name" is specific to data stores with a concept of tables. I imagine that most ORM adapters that connect to data stores would use a model's type as the name for a table that contains instances of that model, but it could very well do something entirely different.

----

All that said, I'm second guessing our consensus on `snake_case` for model types. Certainly most ORM adapters would convert to snake case for table / collection / whatever names. But that's a one time cost per adapter, so it's not a huge burden.

Conversely, JSON-API and common URL conventions typically have dasherized type names. JSON-API doesn't require dasherized, but suggests it. And you'll typically see `/blog-posts` as a URL rather than `/blog_posts`.

I think there's an argument that keeping type strings dasherized is more consistent with Denali core's perspective (data store agnostic), and even helps reinforce that type !== table name.

There's also a good chunk of bikeshedding in this topic, so if others are in favor of snake_case, I'm happy to proceed with that for now and revisit later if needed.

**Comment by knownasilya** [comment]
> I think there's an argument that keeping type strings dasherized is more consistent with Denali core's perspective (data store agnostic), and even helps reinforce that type !== table name.

👍 totally agree. Didn't realize you mean't changing the model type form.

**Comment by acorncom** [comment]
> I think there's an argument that keeping type strings dasherized is more consistent with Denali core's perspective (data store agnostic), and even helps reinforce that type !== table name.

The above sound reasonable to me, but that then leads me to a few other questions ;-)

In the other frameworks I've used, there is generally a distinction between a model (ActiveRecord / ORM-based DB representation) and a serializer / resource.  The model may also be where validations are specified.  When I see model, I normally think ORM layer (with table names, primary keys, validations, etc defined at this layer).

From what it seems like as I look at Denali, what I'm used to seeing called serializers / resources are called models and the ORM data models (with associated validations if so desired) are left to me to put where I see fit.  I understand and am comfortable with defining ORM / models as being outside of Denali's scope, but as an app developer trying to build my app I still **do** need a place for ORM models and validations for my data ... 😀 Are we going to make recommendations on this front?  Where would we suggest those things happen?

Interested in both of your thoughts here ...

**Comment by davewasmer** [comment]
> The model may also be where validations are specified. When I see model, I normally think ORM layer (with table names, primary keys, validations, etc defined at this layer).

I think all that holds true for Denali Models as well. The distinction is that Denali **core** is not aware of these. But whatever ORM adapter you use is.

So, hypothetically, a Knex ORM adapter could use your Denali Model's `type` as the basis for building a table name. Denal core doesn't have any concept of a table name, but the Knex ORM adapter effectively adds that. Another example: the `attr()` helper takes an options object as it's second argument. Denali **core** doesn't actually support any options right now, and may never. But a Knex ORM adapter could support a `primaryKey` option, or an `autoincrement` option, or whatever else it needs.

Continuing with the Knex adapter example, you would never actually define a Knex model by hand as an app developer. You would just install the `denali-knex` addon, define your models as Denali Model classes, and the Knex adapter would scan the available models on initialization of the app, and internally would define Knex models to match your Denali definitions.

So as an end user, the goal is that I would be able to work with Denali Models all the time. But since Denali instances are actually Proxies, I get both the Denali Model API and the Knex Model API in one object, in case I want to do anything that is unique to Knex's functionality.

I realize this is a bit convoluted, and IMO is one of the riskiest aspects of Denali. But it's the only thing I can think of to satisfy my two goals:

1. Bring your own ORM. Building our own is a monumental task, and no universal one exists, so you must be able to bring pretty much any existing ORM to the table.

2. Provide a consistent interface to basic data operations, such that addons which want to integrate with your data model don't require custom code, or require _their_ own adapters to every different ORM interface.

I'm all ears to any improvements to this setup - I'm not a fan of it's complexity, but like I said, best I could come up with for now.

**Comment by davewasmer** [comment]
Closing in light of #114.

Most of Denali's interfaces and conventions revolve around singularized type strings. Model class names, `this.modelFor('blog-post')`, serializer types, etc. So I think singularized makes the most sense internally and #114 corrects the JSON-API serializer by pluralizing those type strings over the wire.
