### ISSUE TITLE
`denali server` crashes, missing dist

### ISSUE THREAD

**Issue by knownasilya** [denali-js/denali#145]
![screen shot 2016-10-11 at 9 26 38 am](https://cloud.githubusercontent.com/assets/34726/19271986/d8341eaa-8f94-11e6-959c-6885649a6747.png)

Using master. I might fix this, but just put it here for now. cc @sivakumar-kailasam 

Probably has to do with https://github.com/denali-js/denali/blob/master/lib/cli/commands/server.js#L81

The following kind of works, except that there are a few issues relating to paths (see my PRs).

```
denali server --output dist
```

**Comment by sivakumar-kailasam** [comment]
Locally i solved this one by linking app and config from the tmp folder passed to _finishBuild in project.js into dist. Not sure if that's the way to go but I did face another issue right after where denali's index.js was trying to load the `./dist` module. Also since the app's index.js refers to the application class inside dist, the symlinking/copying of latest built transpiled files into dist seems to be a hard requirement. Hope these help :)

**Comment by knownasilya** [comment]
@davewasmer looks like we need to fix the dist paths issue if we want to use tmp paths for our builds.

**Comment by knownasilya** [comment]
After all of the fixes, I still get:

![screen shot 2016-10-11 at 9 48 39 am](https://cloud.githubusercontent.com/assets/34726/19272796/f40609ec-8f97-11e6-84bc-81268efd18ac.png)
