### ISSUE TITLE
Add the ability to do unit tests for actions again

### ISSUE THREAD

**Issue by acorncom** [denali-js/denali#166]
They got taken out in https://github.com/denali-js/denali/commit/6f3da1e099f537b7f603dd9ed635b75973ecbb70 but it'd be great to have it back in the long run

**Comment by davewasmer** [comment]
What kind of unit test support are you looking for specifically? I removed the "unit" test there because it wasn't actually really a unit test. It tried to load the entire app, then pull out the action class from the container, which is beyond the scope of an action unit test - it should just import the action file and test something about it's interface directly.

**Comment by davewasmer** [comment]
Closing for now, but feel free to reopen if I misunderstood your intention @acorncom
