### ISSUE TITLE
Print argument descriptions for blueprint help

### ISSUE THREAD

**Issue by davewasmer** [denali-js/denali#203]
Running `denali generate --help` lists the available blueprints and their descriptions, but doesn't show descriptions for the available flags. Same for `denali new` and `denali addon` (which are essentially wrappers over `denali generate app/addon`).

Running any of those commands with `--help` should print out the names and descriptions of the available flags.

**Comment by acorncom** [comment]
@davewasmer For this, currently flags are duplicated between commands and blueprints (which might turn into a maintenance headache in the long run).  Is that something you want to continue doing or should we adjust so that flags are static and retrieved from blueprints by both commands and blueprints?

**Comment by davewasmer** [comment]
I thought there was an `allowExtraArgs` flag on the command that would basically ignore additional arguments, so you didn't have to define them on both (the command would essentially define no arguments, and just pass through whatever was provided to the blueprint). Does that not work?

**Comment by davewasmer** [comment]
This is now fixed in denali-cli with yargs support.
