### ISSUE TITLE
.env is not respected for denali server

### ISSUE THREAD

**Issue by rtablada** [denali-js/denali#283]
When running `denali server` the `.env` file is not loaded to `process.env`.

As noted in the slack channel this may be caused by `Builder` not copying `.env` to `dist`.

However, this may not be ideal either if developers want to publish their `dist` directory.

## Questions

* Can we copy `.env` along with the `package.json` and other existing files in `Builder`?
* If not `denali server` how should load `process.env` for the running server else where?

**Comment by knownasilya** [comment]
The issue with copying the config, is that it will not be clear that the one in the parent directory is not the honored config, especially when we have `denali [warm boot]` that doesn't do the build.

**Comment by davewasmer** [comment]
Hmm, interesting.

I'm inclined to say let's just copy `.env` over during the build (should be trivial, just add to `packageFiles` property of the base Builder class), and add it to the .gitignore file for blueprints (since it should be gitignored anyway). That would likely prevent it from being published in the large majority of deploy scenarios. And regardless, if you use `.env`, you likely know that it shouldn't be published.

> If not denali server how should load process.env for the running server else where?

My goal is for `$ denali server` to be the default (but not exclusive) approach to running Denali in production, including doing things like clustering the app.

**Comment by davewasmer** [comment]
Actually - after a bit more thought on this, I think my suggestion above isn't the right approach.

While .gitignore'ing the `.env` file would prevent publishing in lots of use cases, there's plenty of deployment strategies that don't rely on git. And some of those users might simply copy `dist` to the server somehow and attempt to run it directly, treating it like a black box.

If Denali can be a little smarter about this, it could save a lot of potential pain. If we can only load `.env` from the $PWD, and leave `.env` out of the build, that would close off a potential mistake vector, which is always a plus.

### How it would work

Right now, `denali server --production` attempts to load the app from `dist/` and assumes that it is already built. The directory it attempts to run can be customized via `--output` (slightly confusing, I know, probably need a better/separate flag for that). So to run the current directory rather than `./dist/`, you'd `denali server --production --output .`

We could move `.env` loading from the Denali runtime to the CLI (which actually feels like it belongs in the CLI anyway). The CLI would attempt to load `.env` from the $PWD, not the app directory. Since it spawns the server process, we can inject the environment vars then.

The end result would be:

* In dev, `my-project/$ denali server` loads from `my-project/.env` if present, and builds/runs the app from `my-project/dist/`
* In prod, if you ship the entire app to the server and run `my-project/$ denali server`, it would do the same. The potential mistake vector is still present here, but this should be the least surprising - if you ship the entire `my-project` folder, you shouldn't ship `.env` too.
* In prod, if you ship only `dist/` to the server and run `my-project-dist/$ denali server --output .`, it would attempt to load `my-project-dist/.env`, which would not exist.

Thoughts?

**Comment by knownasilya** [comment]
I like it, but it needs a `--config-path` flag, in case they deploy via CI and it wipes the project dir, the config might live in the users dir instead.

**Comment by davewasmer** [comment]
In my experience, using a `.env` file in production isn't very common. My understanding is that it's commonly used to mimic production in dev (i.e. so you don't have to type each env var every time you run the server), but production would have the environment variables already set, 12-factor style

**Comment by knownasilya** [comment]
Yeah, but more people are doing Docker based deployments, and if the file is there they'll just use it.

**Comment by rtablada** [comment]
I think doing something smart like `if (process.env.DENALI_ENV

**Comment by rtablada** [comment]
I think doing something smart in the CLI itself like 

```js
if (process.env.DENALI_ENV && !options.ignoreDotenv) {
  loadEnv()
}
```

I don't know how `denali server` is starting up the app server but can you pass `.env` variables to that process?

**Comment by rtablada** [comment]
Then have a customizable way for people using docker or whatever to deploy the `dist` directory and they can decide if they want to include `.env` in dist and edit a hook to include it in their build.

**Comment by davewasmer** [comment]
@rtablada:

> ``` if (process.env.DENALI_ENV && !options.ignoreDotenv) {```

What's the goal of the DENALI_ENV check there? Also, btw, I just dropped DENALI_ENV support - we just use the regular NODE_ENV, since literally everywhere we used DENALI_ENV, we also fell back to NODE_ENV, and I didn't see a good reason to keep the additional, identical, non-standard option.

> I don't know how denali server is starting up the app server but can you pass .env variables to that process?

Yep, we just `childProcess.spawn()` it, so it's easy to pass through whatever we want as env vars, either from the CLI's own env, or from config loaded (i.e. via dotenv).

> Then have a customizable way for people using docker or whatever to deploy the dist directory 

I'm not sure what "a customizable way ... to deploy the dist directory" looks like here, given the myriad of different deployment strategies available. Could you elaborate?

I suppose we could look at something like `ember-cli-deploy` for inspiration (i.e. creating a generic deploy pipeline that plugins could fill in), but I worry the pipeline is far less standard for server-side apps, to the point of forcing `denali-deploy` to be generic to the point of useless. 

> they can decide if they want to include .env in dist and edit a hook to include it in their build

Yea, right now this is trivial (add `.env` to your `packageFiles` in `denali-build.js`), but again, I'm not sure I see the use case - isn't the whole point of `.env` files to capture your _development_ environment, which necessarily will be different from your production environment?

**Comment by davewasmer** [comment]
This should be fixed, although I haven't had a chance to test it all together. Closing for now, but feel free to reopen if it needs more work.
