### ISSUE TITLE
Provide an easier way of gaining access to properties attached to the request object

### ISSUE THREAD

**Issue by acburdine** [denali-js/denali#291]
This is more of a request (no pun intended)/question, rather than missing functionality.

Currently, Denali supports express/connect-style middleware in `config/middleware.js`. This works fine, but some middleware libraries (my specific use-case: `cookie-session`) attach properties to the `req` object. The only way to access those properties in an action is through `this.request._incomingMessage.<property>` which seems dirty because it's relying upon access  to private variables. I looked through the Request class and didn't find any other way to get access to the right property, meaning it might be a good idea to have an easier way to access custom properties.

**Comment by davewasmer** [comment]
Hm. We should definitely support this. I think the easiest way would be to switch [this line](https://github.com/denali-js/denali/blob/master/lib/runtime/router.ts#L135) to pass the Denali Request object to the middleware functions, rather than the IncomingMessage object.

The only trick then is to make sure that the Request object matches the Express `req` object interface so that we maintain compatibility. If we can do that, then the Express-based middleware won't know they are running against a Denali Request, and you should be able to access middleware-added properties via `this.request.<property>`.

**Comment by acburdine** [comment]
From a quick glance at the express 4 request api it appears Denali is close to the same spec, so shouldn't be too difficult 😄
