### ISSUE TITLE
Question: GraphQL

### ISSUE THREAD

**Issue by lifeiscontent** [denali-js/denali#413]
Any plans to support GraphQL in Denali?

**Comment by davewasmer** [comment]
@lifeiscontent definitely. That would most likely come as a semi-official addon, i.e. `denali-graphql`. I don't know GraphQL well enough at the moment to comment on how that would be structured, but if you're interested in trying to implement it, I'm happy to brush up on the details and talk through how to approach it.

P.S. Feel free to hop on the Slack team - it's usually a better outlet than an issue to discuss something like this. I'm on there pretty regularly. https://denali-slack.now.sh/

-----

Closing since there is no immediate action here, but happy to reopen to continue the conversation with anyone willing to contribute here.
