### ISSUE TITLE
Email Service

### ISSUE THREAD

**Issue by knownasilya** [denali-js/denali#85]
Is this a thing yet? Just wondering because it's documented [here](http://denali.js.org/canary/guides/application/mailers/#sending-the-email).

I couldn't find any hint of the mailer being integrated into actions.

**Comment by davewasmer** [comment]
WIP at the moment - those docs are evidence of my occasional "docs-driven development" approach. There is no `mail()` method on actions yet. Certainly open to alternatives as well.

**Comment by knownasilya** [comment]
As a service?

**Comment by davewasmer** [comment]
That's certainly an option (sending emails was actually one of the original use cases I had in mind for services, among other things).

My only hesitation with sending emails via a service is that it opens it up for userland code to break framework conventions. I.e. what happens if someone adds their own `mail` service that would override the builtin mail service?

I could see pros and cons here - it's cool to be able to implement framework functionality using already existing features (a kind of dogfooding exercise I suppose). But it also opens up the ability for users to mess with framework conventions (i.e. if I override the `mail` service with my own incompatible service, I lose out on all the benefits of the framework / convention based approach). Do we want to allow that kind of potential footgun?

@tomdale - I know you're out on vacation this week, but whenever you're back, I'd love to hear your thoughts if you have any on this issue.

**Comment by knownasilya** [comment]
> My only hesitation with sending emails via a service is that it opens it up for userland code to break framework conventions. I.e. what happens if someone adds their own mail service that would override the builtin mail service?

Sounds like a nice way to override. The only thing I'd do is print a console log if an addon is overwriting an internal service.

**Comment by davewasmer** [comment]
It is, but my question is do we want to allow overrides? In other words, if mailers are baked in and conventional in Denali, allowing overrides in the public API loses some of that benefit. If I develop some email related addon for denali, now I can't trust that `Action#mail()` does what the docs suggest, since the user can override [1].

I'm starting to think that if we allow overrides, then mailers shouldn't even be baked into the core framework. It could be an officially supported userland addon, similar to how Ember Data is the officially supported data lib, but there are other implementations too.

While I'm not convinced there's enough variation in how email sending is handled that it needs to be an overridable userland thing, I'm starting to lean towards an official userland addon as a starting point, which could be absorbed by core later on once we discover the appropriate patterns. Seems easier to go that direction than the reverse (have it start in core, discover enough variation that it gets extracted into userland later).

----

[1] When I say "can override", I mean the framework allows and even invites overrides. Obviously, this is JavaScript, so a user can override whatever they feel like. I'm more concerned with what the "good citizen" of the Denali ecosystem would be encouraged to do.

**Comment by knownasilya** [comment]
Yeah maybe an addon is the best way and we just include it by default.

Would it provide a service or extend `Action`?

**Comment by davewasmer** [comment]
In that scenario, I say provide as a service. Since Denali auto-loads all of `app/*` into the container, we can keep the `app/mailers` folder structure.

**Comment by knownasilya** [comment]
You'll have to create that repo, I don't think I have the permissions.

**Comment by knownasilya** [comment]
I can't push to the new mailer repo.

**Comment by davewasmer** [comment]
Whoops - should be good to go now

**Comment by knownasilya** [comment]
Still nothing lol

**Comment by acorncom** [comment]
See https://github.com/denali-js/denali-mailer

**Comment by davewasmer** [comment]
Closing in favor of #194
