### ISSUE TITLE
Support adding blueprints via addon

### ISSUE THREAD

**Issue by knownasilya** [denali-js/denali#93]
Register addon `blueprints/<name>` as a blueprint callable by `denali g <name>`.

This is currently a blocker for pulling out the Mailer as an addon.

**Comment by davewasmer** [comment]
We should figure out how to handle collisions in blueprint names. I'm thinking we use the addon load order, last one wins. But it might be nice to be able to reference an addon's blueprint explicitly, i.e. `denali g my-addon:blueprint-name` or something like that.

**Comment by knownasilya** [comment]
That's what I was thinking, namespacing instead of trying to handle clobbering.

**Comment by davewasmer** [comment]
I think both might be useful. I.e. in denali-mailer's case, if it doesn't collide, might as well just be able to type `denali g mailer` instead of `denali g denali-mailer:mailer`.

And even when they do collide, I'd expect the un-namespaced usage to be more common. I.e. I install denali-mailer, plus maybe another addon that adds some functionality specific to an email provider like Sendgrid or something. That addon might _want_ to clobber the mailer blueprint, since it can generate a more useful default blueprint.

**Comment by knownasilya** [comment]
See my comment above.

Ember CLI has a `.ember-cli` file which can specify options. Might be useful to allow the user to set the default version they want, even if an addon clobbers. So if there is:

```sh
denali g test
denali g addona:test
denali g addonb:test
```

Addon B might clobber all of them making `denali g test` run addon b's test blueprint. This could be overridden by setting in `.denali-cli`

```json
{
 "blueprintOverrides": {
    "test": "addona:test"
  }
}
```

**Comment by davewasmer** [comment]
This should be resolved on master now. Feel free to reopen/refile if we are still missing something though.
