### ISSUE TITLE
denali module doesn't reflect in api index page

### ISSUE THREAD

**Issue by knownasilya** [denali-js/denali#94]
This page http://denali.js.org/latest/api/modules/denali/ doesn't get updated when the source
https://github.com/denali-js/denali/blob/master/lib/index.js is updated. The api page above says it's defined here though: https://github.com/denali-js/denali/blob/master/lib/runtime/service.js#L6

**Comment by davewasmer** [comment]
Hm - so that page seems to update okay for me. Can you give it another shot? I've made some changes to the docs build process, perhaps I fixed it by accident.

As for the incorrect source line - either YUIDoc has a bug, or I'm not understanding the syntax, but I can't seem to get it to treat the `lib/index.js` file as the source. It seems like it's basically using the last file it encounters (alphabetically).

**Comment by davewasmer** [comment]
Filed an issue: https://github.com/yui/yuidoc/issues/425

**Comment by davewasmer** [comment]
For now, lets just remove the source links on module pages, since it seems like the Yuidoc issue doesn't seem to be getting much attention.
